-- Avisos e afazeres dos administradores
-- Execute depois de controle_acesso_usuarios.sql.

CREATE TABLE IF NOT EXISTS public.admin_notice_todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    text TEXT NOT NULL,
    priority TEXT NOT NULL DEFAULT 'normal',
    due_date DATE,
    done BOOLEAN NOT NULL DEFAULT false,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    done_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT admin_notice_todos_type_check CHECK (type IN ('notice', 'todo')),
    CONSTRAINT admin_notice_todos_priority_check CHECK (priority IN ('low', 'normal', 'high'))
);

ALTER TABLE public.admin_notice_todos
ADD COLUMN IF NOT EXISTS priority TEXT NOT NULL DEFAULT 'normal',
ADD COLUMN IF NOT EXISTS due_date DATE;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'admin_notice_todos_priority_check'
    ) THEN
        ALTER TABLE public.admin_notice_todos
        ADD CONSTRAINT admin_notice_todos_priority_check CHECK (priority IN ('low', 'normal', 'high'));
    END IF;
END $$;

ALTER TABLE public.admin_notice_todos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins veem avisos e afazeres" ON public.admin_notice_todos;
CREATE POLICY "Admins veem avisos e afazeres"
ON public.admin_notice_todos
FOR SELECT
TO authenticated
USING (public.is_access_admin());

DROP POLICY IF EXISTS "Admins criam avisos e afazeres" ON public.admin_notice_todos;
CREATE POLICY "Admins criam avisos e afazeres"
ON public.admin_notice_todos
FOR INSERT
TO authenticated
WITH CHECK (public.is_access_admin());

DROP POLICY IF EXISTS "Admins atualizam avisos e afazeres" ON public.admin_notice_todos;
CREATE POLICY "Admins atualizam avisos e afazeres"
ON public.admin_notice_todos
FOR UPDATE
TO authenticated
USING (public.is_access_admin())
WITH CHECK (public.is_access_admin());

DROP POLICY IF EXISTS "Admins removem avisos e afazeres" ON public.admin_notice_todos;
CREATE POLICY "Admins removem avisos e afazeres"
ON public.admin_notice_todos
FOR DELETE
TO authenticated
USING (public.is_access_admin());
