-- Avisos e afazeres dos administradores
-- Execute depois de controle_acesso_usuarios.sql.

CREATE TABLE IF NOT EXISTS public.admin_notice_todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    text TEXT NOT NULL,
    done BOOLEAN NOT NULL DEFAULT false,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    done_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT admin_notice_todos_type_check CHECK (type IN ('notice', 'todo'))
);

ALTER TABLE public.admin_notice_todos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins veem avisos e afazeres" ON public.admin_notice_todos;
CREATE POLICY "Admins veem avisos e afazeres"
ON public.admin_notice_todos
FOR SELECT
TO authenticated
USING (public.is_access_admin());

DROP POLICY IF EXISTS "Admins criam avisos e afazeres" ON public.admin_notice_todos;
CREATE POLICY "Admins criam avisos e afazeres"
ON public.admin_notice_todos
FOR INSERT
TO authenticated
WITH CHECK (public.is_access_admin());

DROP POLICY IF EXISTS "Admins atualizam avisos e afazeres" ON public.admin_notice_todos;
CREATE POLICY "Admins atualizam avisos e afazeres"
ON public.admin_notice_todos
FOR UPDATE
TO authenticated
USING (public.is_access_admin())
WITH CHECK (public.is_access_admin());

DROP POLICY IF EXISTS "Admins removem avisos e afazeres" ON public.admin_notice_todos;
CREATE POLICY "Admins removem avisos e afazeres"
ON public.admin_notice_todos
FOR DELETE
TO authenticated
USING (public.is_access_admin());
