-- Arquivos de impressao dos administradores
-- Execute depois de controle_acesso_usuarios.sql.
--
-- Observacao: os arquivos ficam salvos como data_url em texto.
-- Use para arquivos pequenos de impressao recorrente, como regras, avisos e PDFs simples.

CREATE TABLE IF NOT EXISTS public.admin_print_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    file_name TEXT NOT NULL,
    mime_type TEXT NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    file_data TEXT NOT NULL,
    notes TEXT,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE public.admin_print_files ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins veem impressos" ON public.admin_print_files;
CREATE POLICY "Admins veem impressos"
ON public.admin_print_files
FOR SELECT
TO authenticated
USING (public.is_access_admin());

DROP POLICY IF EXISTS "Admins criam impressos" ON public.admin_print_files;
CREATE POLICY "Admins criam impressos"
ON public.admin_print_files
FOR INSERT
TO authenticated
WITH CHECK (public.is_access_admin());

DROP POLICY IF EXISTS "Admins removem impressos" ON public.admin_print_files;
CREATE POLICY "Admins removem impressos"
ON public.admin_print_files
FOR DELETE
TO authenticated
USING (public.is_access_admin());
