-- Reservas semanais recorrentes de bases/carrinhos.
-- Execute este arquivo uma vez no SQL Editor do Supabase.

CREATE TABLE IF NOT EXISTS public.weekly_reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    weekday SMALLINT NOT NULL CHECK (weekday BETWEEN 0 AND 6),
    start_time TIME NOT NULL,
    class_id BIGINT NOT NULL REFERENCES public.classes(id) ON DELETE CASCADE,
    teacher_id BIGINT NOT NULL REFERENCES public.teachers(id) ON DELETE CASCADE,
    device_type TEXT NOT NULL,
    group_name TEXT NOT NULL,
    reminder_minutes INTEGER NOT NULL DEFAULT 10
        CHECK (reminder_minutes BETWEEN 1 AND 180),
    notes TEXT,
    active BOOLEAN NOT NULL DEFAULT true,
    created_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

CREATE INDEX IF NOT EXISTS weekly_reservations_schedule_idx
ON public.weekly_reservations (weekday, start_time)
WHERE active = true;

ALTER TABLE public.weekly_reservations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Leitura geral reservas semanais" ON public.weekly_reservations;
CREATE POLICY "Leitura geral reservas semanais"
ON public.weekly_reservations
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS "Equipe cria reservas semanais" ON public.weekly_reservations;
CREATE POLICY "Equipe cria reservas semanais"
ON public.weekly_reservations
FOR INSERT
TO authenticated
WITH CHECK (public.is_access_staff());

DROP POLICY IF EXISTS "Equipe atualiza reservas semanais" ON public.weekly_reservations;
CREATE POLICY "Equipe atualiza reservas semanais"
ON public.weekly_reservations
FOR UPDATE
TO authenticated
USING (public.is_access_staff())
WITH CHECK (public.is_access_staff());

DROP POLICY IF EXISTS "Equipe remove reservas semanais" ON public.weekly_reservations;
CREATE POLICY "Equipe remove reservas semanais"
ON public.weekly_reservations
FOR DELETE
TO authenticated
USING (public.is_access_staff());
