-- Tabela de Turmas
CREATE TABLE classes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    shift VARCHAR NOT NULL,
    students INT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Tabela de Professores
CREATE TABLE teachers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL,
    subject VARCHAR,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Tabela de Dispositivos
CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR NOT NULL,
    serial_number TEXT,
    patrimony VARCHAR,
    imei TEXT,
    counter_number TEXT NOT NULL DEFAULT 's/n',
    "group" VARCHAR NOT NULL,
    status VARCHAR NOT NULL DEFAULT 'Disponível',
    observations TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Tabela de Empréstimos
CREATE TABLE loans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
    teacher_id BIGINT REFERENCES teachers(id) ON DELETE CASCADE,
    device_type VARCHAR NOT NULL,
    quantity INT NOT NULL,
    loan_type VARCHAR NOT NULL,
    group_name VARCHAR,
    date_time VARCHAR NOT NULL,
    releaser VARCHAR NOT NULL,
    observations TEXT,
    returned BOOLEAN DEFAULT false,
    return_date_time VARCHAR,
    return_quantity INT,
    return_status VARCHAR,
    return_observations TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- Desabilita RLS para todas as tabelas (para testes)
ALTER TABLE classes DISABLE ROW LEVEL SECURITY;
ALTER TABLE teachers DISABLE ROW LEVEL SECURITY;
ALTER TABLE devices DISABLE ROW LEVEL SECURITY;
ALTER TABLE loans DISABLE ROW LEVEL SECURITY;
