-- Historico administrativo de dispositivos
-- Registra criacao, edicao, exclusao e mudancas de manutencao feitas pelo app.
-- Execute controle_acesso_usuarios.sql antes deste arquivo.

CREATE TABLE IF NOT EXISTS public.device_change_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT,
    action TEXT NOT NULL,
    changed_by TEXT,
    previous_data JSONB,
    new_data JSONB,
    notes TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    CONSTRAINT device_change_history_action_check CHECK (
        action IN ('created', 'updated', 'deleted', 'maintenance_in', 'maintenance_out')
    )
);

ALTER TABLE public.device_change_history ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios autenticados veem historico de dispositivos" ON public.device_change_history;
CREATE POLICY "Usuarios autenticados veem historico de dispositivos"
ON public.device_change_history
FOR SELECT
TO authenticated
USING (true);

DROP POLICY IF EXISTS "Admins registram historico de dispositivos" ON public.device_change_history;
CREATE POLICY "Admins registram historico de dispositivos"
ON public.device_change_history
FOR INSERT
TO authenticated
WITH CHECK (public.is_access_admin());
